# -*- coding: utf-8 -*-
"""housing ana.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lq-sBpu23WY3zUykLrAQKWm6Z70liZZy
"""

import pandas as pd

data = pd.read_csv("/content/file(3).csv")

data.head()

data.count()

data.isnull().sum()

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(data.isnull())
plt.show()

data.head()

data.dtypes

data.date = pd.to_datetime(data.date)

data.dtypes

data["year"] = data.date.dt.year

data.head()

data.insert(1,"month",data.date.dt.month)
data.head()

data = data.drop(["month","year"],axis = 1)

data.head()

data[data.no_of_crimes == 0]



data["year"] = data.date.dt.year

data.head()

df1 = data[data.area=="england"]
df1

df1.groupby("year").average_price.max()

data.groupby("area").no_of_crimes.max()

data.groupby("area").no_of_crimes.min()

data[data.average_price < 100000].area.value_counts()